name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: reactnativecommunity/react-native-android:latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Buildozer & Cython
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython

      - name: Install Android SDK packages
        env:
          ANDROID_SDK_ROOT: /opt/android-sdk
          ANDROID_HOME: /opt/android-sdk
          PATH: /opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:$PATH
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip -d /opt/android-sdk/cmdline-tools
          mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Patch buildozer.spec (ensure 35.0.0 is pinned)
        run: |
          sed -i 's/^android.build_tools_version *= *.*/android.build_tools_version = 35.0.0/' buildozer.spec
          sed -i '/^android.gradle_build_tools *= *.*/d' buildozer.spec

      - name: Clean Previous Build
        run: |
          rm -rf .buildozer bin

      - name: Build APK (Debug)
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AddressNavigator-APK-2025
          path: bin/*.apk
