name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04   # Full VM with sudo/bash/git/tar

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk
      # Prefer Build-Tools 35 once installed so aidl/aapt2 resolve to the pinned version
      PATH: /usr/local/lib/android/sdk/build-tools/35.0.0:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/cmdline-tools/latest/bin:$PATH

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up Java 17 (AGP-compatible)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set Up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install System Dependencies
        run: |
          set -euxo pipefail
          sudo dpkg --add-architecture i386
          sudo apt-get update -y
          sudo apt-get install -y \
            git tar wget curl unzip zip ca-certificates \
            autoconf automake libtool libtool-bin autopoint m4 pkg-config \
            build-essential cmake zlib1g-dev libffi-dev libssl-dev \
            libstdc++6:i386 zlib1g:i386 libncurses6:i386 libtinfo6:i386 \
            patch rsync
          git --version
          tar --version
          java -version
          python3 --version
          pip --version

      - name: Install Buildozer & Cython
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython wheel

      - name: Install Android cmdline-tools
        run: |
          set -euxo pipefail
          sudo mkdir -p "$ANDROID_SDK_ROOT"
          sudo chown -R "$USER:$USER" "$ANDROID_SDK_ROOT"
          cd "$ANDROID_SDK_ROOT"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/ || true

      - name: Accept Android SDK licenses
        env:
          PATH: /usr/local/lib/android/sdk/cmdline-tools/latest/bin:$PATH
        run: |
          set -euxo pipefail
          sdkmanager --version
          printf 'y\n%.0s' {1..60} | sdkmanager --licenses

      - name: Install Android SDK packages (API 35 + Build-Tools 35.0.0)
        env:
          PATH: /usr/local/lib/android/sdk/cmdline-tools/latest/bin:$PATH
        run: |
          set -euxo pipefail
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Set Up Android NDK r26d
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          link-to-sdk: true

      - name: Export Env (pin aidl path to 35.0.0)
        run: |
          set -euxo pipefail
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "ANDROIDNDK=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
          echo "/usr/local/lib/android/sdk/build-tools/35.0.0" >> $GITHUB_PATH
          echo "/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_PATH
          echo "/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Patch buildozer.spec and clean
        run: |
          set -euxo pipefail
          # Pin Build-Tools (prevents attempts to fetch 36)
          sed -i 's/^android.build_tools_version *= *.*/android.build_tools_version = 35.0.0/' buildozer.spec || true
          # Remove unknown/ignored key if present
          sed -i '/^android.gradle_build_tools *= *.*/d' buildozer.spec || true
          # Ensure API is set
          grep -q '^android.api' buildozer.spec || echo 'android.api = 35' >> buildozer.spec
          rm -rf .buildozer bin

      - name: Build APK (Debug)
        run: |
          set -euxo pipefail
          which sdkmanager || true
          which aidl || true
          which aapt2 || true
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AddressNavigator-APK-2025
          path: bin/*.apk
          retention-days: 30
